apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Values.configName }}
data:
  appsettings.json:
    {{ .Values.data | toPrettyJson | quote }}