apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          volumeMounts:
            - mountPath: /app/sharedsettings.{{.Values.environment}}.json
              name: shared-config
              subPath: sharedsettings.json
            - mountPath: /app/appsettings.{{.Values.environment}}.json
              name: competition-config
              subPath: appsettings.json
            - mountPath: /certs/aspnetcore-cert.pfx
              name: cert-volume
              subPath: aspnetcore-cert.pfx
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              port: {{ .Values.probes.liveness.port }}
              path:  {{ .Values.probes.liveness.path }}
              scheme: "HTTPS"
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          env:
            - name: Token__Value
              valueFrom:
                secretKeyRef:
                  key: Token
                  name: {{ .Chart.Name }}-secret
            - name: Kestrel__Certificates__Default__Path
              value: /certs/aspnetcore-cert.pfx
            - name: Kestrel__Certificates__Default__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: certificatePassword
      volumes:
        - name: shared-config
          configMap:
            name: {{ .Values.sharedConfigName }}
        - name: competition-config
          configMap:
            name: {{ .Values.configName }}
        - name: cert-volume
          secret:
            secretName: {{ .Chart.Name }}-secret
            items:
              - key: certificate
                path: aspnetcore-cert.pfx
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}