apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      name: https
  selector:
    app: {{ .Chart.Name }}