version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - metrics

    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment: 
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        networks:
            - metrics
        
    elasticsearch:
        image: elasticsearch:7.6.1
        environment:
            - discovery.type=single-node
        networks: 
            - metrics
        ports:
            - "9200:9200"
            - "9300:9300"
    
    redis:
        image: redis
        environment: 
            - REDIS_PASSWORD=password
        networks: 
            - metrics
        ports:
            - "6379:6379"
    consul:
        image: consul
        networks:
            - metrics
        ports:
            - "8500:8500"

networks: 
    metrics:
        driver: bridge
volumes: 
    certs:
        name: ${CERTS_PATH}
        external: false