version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5601:5601"
            - "15672:15672"
        environment: 
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
    elasticsearch:
        image: elasticsearch:7.6.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node

