version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - metrics

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment: 
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        networks:
            - metrics
        
    elasticsearch:
        image: elasticsearch:7.6.1
        environment:
            - discovery.type=single-node
        networks: 
            - metrics
        ports:
            - "9200:9200"
            - "9300:9300"
    
    redis:
        image: redis
        environment: 
            - REDIS_PASSWORD=password
        networks: 
            - metrics
        ports:
            - "6379:6379"
    
    broker-console:
        container_name: broker-console
        build:
            context: .
            dockerfile: metrics.Broker.Console/Dockerfile
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
        depends_on: 
            - postgres
            - redis
            - rabbitmq
        networks: 
            - metrics

    competition-hosted:
        container_name: competition-hosted
        build:
            context: .
            dockerfile: Competition.Hosted/Dockerfile
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
        networks: 
            - metrics
        depends_on: 
            - elasticsearch
            - rabbitmq

    metrics-web:
        container_name: metrics-webapi
        build: 
            context: .
            dockerfile: metrics/Dockerfile
        env_file: 
             - docker-compose.env
        networks: 
            - metrics
        ports: 
            - "1745:1745"
            - "1746:1746"
        depends_on: 
            - broker-console
        volumes: 
            - certs:/https/

networks: 
    metrics:
        driver: bridge
volumes: 
    certs:
        name: ${CERTS_PATH}
        external: false