image: metrics-competition
tag: latest
imagePullPolicy: IfNotPresent
configName: metrics-competition-config
sharedConfigName: metrics-shared-config
certificatePassword: '358359'
port: 443
labels:
  app: metrics-competition
shared:
  RedisConnectionStringLock: 'redis-master,password=password'
  CacheOptions:
    Configuration: 'redis-master,password=password'
    Instance: 'UserTokens:'
  KafkaConfiguration:
    Servers: 'kafka'
  ElasticOptions:
    Host: 'http://elasticsearch-master:9200'
  NLog:
    extensions:
      - assembly: 'NLog.Targets.ElasticSearch'
    targets:
      main:
        type: 'BufferingWrapper'
        flushTimeout: 5000
        target:
          type: 'ElasticSearch'
          uri: 'http://elasticsearch-master:9200'
        fields:
          - name: 'StackTrace'
            layout: '${exception:format=ToString,StackTrace}${newline}'
      logconsole:
        type: 'Console'
    rules:
      - logger: '*'
        minLevel: 'Error'
        writeTo: 'main'
data:
  ConnectionStrings:
    DataContext: 'Host=postgresql;Port=5432;Database=repost_ctx;UserId=postgres;Password=password'
  CompetitionOptions:
    CityId: '97'
  VkontakteOptions:
    AppId: '5662498'
    AppSecret: 'mKuNcx99X552UoVdeTNO'
    AppScope: '111111111'
    Fields:
      - first_name
      - photo_50
      - last_name
    ApiVersion: '5.103'
      