apiVersion: v1
kind: Service
metadata:
  name: metrics-elastic-service
  namespace: metrics-app
  labels:
    app: metrics-elastic-service
spec:
  selector:
    app: metrics-elastic
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: rest
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: node