apiVersion: "apps/v1"
kind: Deployment
metadata:
  namespace: metrics-app
  name: metrics-postgres
  labels:
    app: metrics-postgres
spec:
  selector:
    matchLabels:
      app: metrics-postgres
  template:
    metadata:
      labels:
        app: metrics-postgres
    spec:
      containers:
        - name: metrics-postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metrics-secret
                  key: postgres_password
  strategy:
    type: RollingUpdate