apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume
  labels:
    app: postgres-volume
  namespace: metrics-app
spec:
  storageClassName: metrics-volume
  resources:
    requests:
      storage: 1Gi