apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metrics-app
  name: metrics-rabbitmq
  labels:
    app: metrics-rabbitmq
spec:
  selector:
    matchLabels:
      app: metrics-rabbitmq
  template:
    metadata:
      labels:
        app: metrics-rabbitmq
    spec:
      containers:
        - name: metrics-rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672