apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: site-fetcher-job
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: site-fetcher-job
              image: site-fetcher
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 10m
                  memory: 30Mi
              env:
                - name: CITY_ID
                  value: "97"
                - name: ACCESS_TOKEN
                  value: ""
                - name: VERSION
                  value: "5.124"
                - name: ES
                  value: "http://elasticsearch-elasticsearch-master:9200"
              command:
                - /main
  schedule: "10 * * * *"