apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metrics-ui-ingress
  namespace: default
  labels:
    app: metrics-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  rules:
    - host: metrics-ui
      http:
        paths:
          - backend:
              serviceName: metrics-ui
              servicePort: 80
            path: /
          - backend:
              serviceName: metrics-gateway
              servicePort: 80
            path: /api
          - backend:
              serviceName: metrics-gateway
              servicePort: 80
            path: /notifications
  tls:
    - secretName: etsencrypt-staging
      hosts:
        - metrics-ui